# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
 
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            FUNCTION_NAME=basketball_reference_scraper
            ENTRYPOINT=main
            GCP_PROJECT=nba-predictions-dev
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --entry-point $ENTRYPOINT \
              --runtime python37 \
              --trigger-http \
              --source ./scraper/ \
              --project $GCP_PROJECT
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build:
      - deploy:
          filters:
            branches:
              only:
                - main
